import { ASSEMBLY_BOARD, MODULE_CONFIG, CORE_MODULE, createLoadout as createRawLoadout, getFootprintCells, getInstalledEntries, getModuleById } from "../src/config/module-config.js";
import { MAX_SKILL_MODULES, calculateFinalStats, countSkillModules, pruneDisconnected, validateLoadout } from "../src/systems/ModuleSystem.js";
import { CollisionSystem, circleIntersects, circleRectIntersects } from "../src/systems/CollisionSystem.js";
import { WeaponSystem } from "../src/systems/WeaponSystem.js";
import { SkillSystem } from "../src/systems/SkillSystem.js";
import { decodeLoadoutCode, encodeLoadoutCode } from "../src/systems/LoadoutCodec.js";
import { GAME_CONFIG, PLAYER_BASE_STATS, SONIC_WAVE_CONFIG } from "../src/config/game-config.js";
import { ENEMY_CONFIG, createBossDefinition } from "../src/config/enemy-config.js";
import { LEVELS } from "../src/config/level-config.js";
import { getEnvironmentPool } from "../src/config/environment-config.js";
import { DODGE_DIFFICULTIES, getDodgeDifficulty } from "../src/config/dodge-config.js";
import { Player } from "../src/entities/Player.js"; import { Projectile } from "../src/entities/Projectile.js"; import { Wingman } from "../src/entities/Wingman.js"; import "../src/entities/Decoy.js"; import { Game } from "../src/core/Game.js";

// Keep the older fixture layouts centered when the production board grows from 9x9 to 15x15.
const createLoadout = (spec = {}) => createRawLoadout({ ...spec, modules: (spec.modules ?? []).map((entry) => ({ ...entry, x: entry.x == null ? entry.x : entry.x + 3, y: entry.y == null ? entry.y : entry.y + 3 })) });

const output = document.querySelector("#test-output"); const results = [];
function assert(condition, message) { if (!condition) throw new Error(message); }
function test(name, callback) { try { callback(); results.push(`PASS ${name}`); } catch (error) { results.push(`FAIL ${name}\n  ${error.message}`); } }

test("enemy base health values", () => { const hp = Object.fromEntries(ENEMY_CONFIG.map((enemy) => [enemy.type, enemy.hp])); assert(hp.scout === 5 && hp.swift === 10 && hp.guardian === 20, "enemy base health values are incorrect"); });
test("50 level campaign and boss schedule", () => { assert(LEVELS.length === 50, "level count"); assert([5, 10, 15, 20, 25, 30, 35, 40, 45, 50].every((number) => LEVELS[number - 1].boss), "boss schedule"); assert(LEVELS[49].hpMultiplier > LEVELS[0].hpMultiplier && LEVELS[49].enemyPool.length > LEVELS[0].enemyPool.length, "difficulty did not grow"); const boss = createBossDefinition(50); assert(boss.boss && boss.hp > createBossDefinition(5).hp && boss.bossSkills.includes("radial"), "boss scaling"); });
test("special environments unlock after level 25", () => { assert(LEVELS[24].environmentPool.length === 0 && !LEVELS[24].environment, "environment unlocked too early"); assert(LEVELS[25].environmentPool.length > 0 && LEVELS[25].environment, "environment missing from level 26"); assert(getEnvironmentPool(50).length >= 4, "late environments missing"); });
test("dodge mode difficulty and hazard generation", () => { assert(DODGE_DIFFICULTIES.length === 3 && getDodgeDifficulty("nightmare").speed > getDodgeDifficulty("easy").speed, "dodge difficulties are incomplete"); const game = Object.create(Game.prototype); game.bounds = { width: 480, height: 854 }; game.dodgeDifficulty = getDodgeDifficulty("hard"); game.elapsed = 0; game.dodgePatternIndex = 0; game.projectiles = []; game.spawnDodgePattern(); assert(game.projectiles.length > 0 && game.projectiles.every((projectile) => projectile.team === "enemy" && projectile.dodgeBullet), "dodge mode did not create hazard projectiles"); });
test("boss summon configuration and wave", () => { const boss = createBossDefinition(25); assert(boss.summon.interval < createBossDefinition(5).summon.interval && boss.summon.count === 2, "boss summon scaling"); const game = Object.create(Game.prototype); game.boss = { x: 240, y: 120, hp: 100, definition: boss }; game.bossSummonTimer = 0; game.bossSummonCount = 0; game.enemies = [game.boss]; game.levelNumber = 25; game.levelConfig = { hpMultiplier: 1.5, speedMultiplier: 1.2 }; game.bounds = { width: 480, height: 854 }; const minions = game.updateBossSummons(0.1); assert(minions.length === 2 && minions.every((enemy) => enemy.summoned && !enemy.boss), "boss did not summon minions"); game.enemies.push(...minions); game.bossSummonTimer = 0; assert(game.updateBossSummons(0.1).length === 2, "boss summon cooldown or cap incorrect"); });
test("skill modules keep nine-module limit while regular total limit is removed", () => { const modules = [{ moduleId: "special-chainsaw", x: 4, y: 3 }, { moduleId: "special-chainsaw", x: 2, y: 3 }, { moduleId: "special-chainsaw", x: 0, y: 3 }, { moduleId: "special-chainsaw", x: -2, y: 3 }, { moduleId: "special-chainsaw", x: 6, y: 3 }, { moduleId: "special-chainsaw", x: 8, y: 3 }, { moduleId: "special-chainsaw", x: 10, y: 3 }, { moduleId: "special-chainsaw", x: 4, y: 5 }, { moduleId: "special-chainsaw", x: 2, y: 5 }, { moduleId: "special-chainsaw", x: 0, y: 5 }]; const manySkills = createLoadout({ modules }); assert(MAX_SKILL_MODULES === 9 && countSkillModules(manySkills) === 10 && !validateLoadout(manySkills).valid, "tenth skill module should be rejected"); });

test("15x15 board and centered core", () => { assert(ASSEMBLY_BOARD.columns === 15 && ASSEMBLY_BOARD.rows === 15, "board size"); assert(ASSEMBLY_BOARD.corePosition.x === 7 && ASSEMBLY_BOARD.corePosition.y === 7 && CORE_MODULE.type === "core", "core position"); });
test("multi-cell electric whirlwind loadout", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-nest", x: 1, y: 4 }, { moduleId: "weapon-electric-whirlwind", x: 3, y: 3 }] }); assert(validateLoadout(loadout).valid, "connected loadout"); const cells = getModuleById("weapon-electric-whirlwind").footprint.cells; assert(cells.length === 3 && cells.every(([x]) => x === 0), "vertical three-cell footprint"); });
test("stats merge", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }, { moduleId: "special-wingman", x: 3, y: 4 }] }); const stats = calculateFinalStats(PLAYER_BASE_STATS, getInstalledEntries(loadout).map(({ module }) => module)); assert(stats.maxHp === PLAYER_BASE_STATS.maxHp && stats.moveSpeed === PLAYER_BASE_STATS.moveSpeed && stats.attackSpeed === PLAYER_BASE_STATS.attackSpeed, "base stats changed"); });
test("energy aggregator adds attack speed and is an automatic module", () => { const aggregator = getModuleById("special-energy-aggregator"); const boosted = calculateFinalStats(PLAYER_BASE_STATS, [aggregator, aggregator]); const capped = calculateFinalStats(PLAYER_BASE_STATS, Array.from({ length: 12 }, () => aggregator)); assert(MODULE_CONFIG.weapons.includes(aggregator) && !MODULE_CONFIG.specials.includes(aggregator) && aggregator.type === "weapon" && !aggregator.skill && aggregator.footprint.cells.length === 1 && aggregator.shareCode === 12, "aggregator category configuration missing"); assert(boosted.attackSpeed === 1.4 && capped.attackSpeed === GAME_CONFIG.player.maxAttackSpeed, `invalid attack speed: ${boosted.attackSpeed}/${capped.attackSpeed}`); });
test("automatic fire interval follows attack speed", () => { const player = { x: 240, y: 700, stats: { attackSpeed: 1.2 }, loadout: createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon(_id, interval) { this.interval = interval; } }; new WeaponSystem().firePlayer(player, []); const wingman = new Wingman({ x: 240, y: 700, stats: { attackSpeed: 2 } }); wingman.fire(); assert(Math.abs(player.interval - 5) < 0.001 && Math.abs(wingman.fireTimer - 1 / 6) < 0.001, `automatic intervals did not scale: ${player.interval}/${wingman.fireTimer}`); });
test("combat module is optional", () => { const loadout = createLoadout({ modules: [] }); assert(validateLoadout(loadout).valid, "empty loadout should enter battle"); });
test("loadout code round trip", () => { const source = createLoadout({ modules: [{ moduleId: "weapon-electric-whirlwind", x: 3, y: 3 }, { moduleId: "special-optical", x: 5, y: 4, rotation: 1 }] }); const code = encodeLoadoutCode(source); const restored = decodeLoadoutCode(code).loadout; const signature = (loadout) => loadout.modules.map(({ moduleId, x, y, rotation }) => `${moduleId}:${x}:${y}:${rotation}`).sort().join("|"); assert(code.startsWith("!1") && !code.includes("weapon") && !code.includes("special"), "code exposes module ids"); assert(signature(restored) === signature(source), "loadout was not restored exactly"); });
test("loadout code validates checksum and module codes", () => { const codes = [...MODULE_CONFIG.weapons, ...MODULE_CONFIG.specials].map((module) => module.shareCode); assert(new Set(codes).size === codes.length && codes.every((code) => Number.isInteger(code) && code > 0), "module share codes are not stable and unique"); const code = encodeLoadoutCode(createLoadout({ modules: [{ moduleId: "weapon-electric-whirlwind", x: 3, y: 3 }] })); const last = code.at(-1); const corrupted = `${code.slice(0, -1)}${last === "0" ? "1" : "0"}`; let rejected = false; try { decodeLoadoutCode(corrupted); } catch { rejected = true; } assert(rejected, "corrupted code was accepted"); });
test("player invulnerability after damage", () => { const player = new Player({ x: 240, y: 700, stats: PLAYER_BASE_STATS, loadout: createLoadout({ modules: [] }) }); player.damage(5); assert(player.hp === 95 && player.invulnerabilityTimer === 1, "first damage was not applied"); player.damage(5); assert(player.hp === 95, "damage applied during invulnerability"); player.update(1.01, { pointer: { active: false }, getMovementVector: () => ({ x: 0, y: 0 }) }, GAME_CONFIG.canvas); player.damage(5); assert(player.hp === 90 && player.invulnerabilityTimer === 1, "damage did not return after invulnerability"); });
test("new weapon configuration", () => { assert(MODULE_CONFIG.weapons.length === 8, "weapon count"); assert(["weapon-single", "weapon-twin", "weapon-spread", "weapon-missile", "weapon-boomerang"].every((id) => !getModuleById(id)), "removed weapon modules remain"); const nest = getModuleById("weapon-nest"); assert(nest.behavior.projectile.color === "#ef294d" && nest.behavior.projectile.speed === 580 && nest.behavior.projectile.radius === 18 && nest.behavior.projectile.explosionRadius === 72 && nest.behavior.projectile.homingDelay === 0.42 && nest.behavior.spreadAngle === 0.18, "nest tuning"); assert(getModuleById("weapon-ball-lightning").behavior.projectile.radius === 12 && getModuleById("weapon-ball-lightning").behavior.projectile.growthRate === 8.8, "ball lightning size"); const whirlwind = getModuleById("weapon-electric-whirlwind"); assert(whirlwind.footprint.cells.length === 3 && whirlwind.footprint.cells.every(([x]) => x === 0) && whirlwind.behavior.projectile.damage === 3 && whirlwind.behavior.projectile.radius === 76 && whirlwind.behavior.projectile.speed === 520 && whirlwind.behavior.projectile.returnTimeout === 3 && whirlwind.behavior.projectile.emergencyReturnSpeed === 1800 && whirlwind.behavior.projectile.rearmDelay === 0.6 && whirlwind.behavior.damageInterval === 0.1, "whirlwind tuning"); const lightning = getModuleById("weapon-lightning-generator"); assert(lightning.footprint.cells.length === 2 && lightning.behavior.fireRate === 0.5 && lightning.behavior.fireInterval === 2 && lightning.behavior.projectile.damage === 7 && lightning.behavior.projectile.chainRadius === 200 && lightning.behavior.projectile.chainLife === 0.25 && lightning.behavior.projectile.flashDuration === 0.045, "lightning generator tuning"); });
test("updated special module footprints", () => { const zero = getModuleById("special-zero"); const wingman = getModuleById("special-wingman"); assert(zero.footprint.cells.length === 3 && zero.footprint.cells.every(([, y]) => y === 0), "zero domain is horizontal three-cell"); assert(wingman.footprint.cells.length === 3 && wingman.footprint.cells.every(([, y]) => y === 0), "wingman is horizontal three-cell"); });

test("nest missiles spread before homing", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const makeEnemy = (id, x) => ({ id, x, y: 240, hp: 10 }); const enemies = [makeEnemy("left", 80), makeEnemy("mid", 240), makeEnemy("right", 400)]; const missiles = new WeaponSystem().firePlayer(player, enemies); assert(new Set(missiles.map((missile) => missile.target?.id)).size === 3, "nest targets are not distributed"); const initialVx = missiles.map((missile) => missile.vx); missiles[0].update(0.2, enemies); assert(missiles[0].vx === initialVx[0], "nest homed before spread delay"); missiles[0].update(0.3, enemies); assert(missiles[0].vx !== initialVx[0], "nest did not start homing after delay"); });
test("nest missile creates visible explosion event", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const projectile = new WeaponSystem().firePlayer(player, [])[0]; const enemy = { id: "target", x: projectile.x, y: projectile.y, radius: 10, hp: 10, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return this.hp <= 0; } }; const result = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [projectile] }); assert(projectile.kind === "nestMissile" && Math.abs(Math.hypot(projectile.vx, projectile.vy) - 580) < 0.001 && result.explosionEvents.length === 1 && result.explosionEvents[0].radius === 72, `nest explosion event missing: kind=${projectile.kind}, speed=${Math.hypot(projectile.vx, projectile.vy)}, radius=${projectile.explosionRadius}, events=${result.explosionEvents.length}`); });
test("lightning generator chains unique nearby targets", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-lightning-generator", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const makeEnemy = (id, x, y) => ({ id, x, y, radius: 8, hp: 10, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return this.hp <= 0; } }); const enemies = [makeEnemy("front", 240, 500), makeEnemy("near", 240, 570), makeEnemy("far", 400, 570), makeEnemy("offscreen", 500, 570), makeEnemy("back", 240, 820)]; const projectile = new WeaponSystem().firePlayer(player, enemies)[0]; assert(projectile.kind === "chainLightning" && projectile.target.id === "near" && projectile.chainRadius === 200 && projectile.life === 0.25, "lightning target or lifetime incorrect"); const result = new CollisionSystem().resolve({ player, enemies, projectiles: [projectile] }); assert(result.damageEvents.length === 3 && enemies.filter((enemy) => enemy.hp === 3).length === 3 && enemies[3].hp === 10 && enemies[4].hp === 10, "lightning chain did not hit only visible unique targets"); });
test("weapon origin follows module", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-ricochet", x: 5, y: 4 }] }); const player = { x: 100, y: 200, loadout, canFireWeapon: () => true, armWeapon: () => {} }; const projectile = new WeaponSystem().firePlayer(player, [])[0]; assert(projectile.x === 113 && projectile.y === 192, "origin incorrect"); });
test("electric whirlwind returns and deals area damage", () => { const player = { x: 100, y: 300, loadout: createLoadout({ modules: [{ moduleId: "weapon-electric-whirlwind", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const projectile = new WeaponSystem().firePlayer(player, [])[0]; assert(projectile.kind === "electricWhirlwind" && projectile.whirlwind && projectile.vy < 0, "whirlwind did not launch upward"); projectile.y = 20; projectile.update(0.01, []); assert(projectile.phase === 1, "whirlwind did not turn at top"); const enemy = { id: "near", x: projectile.x + 15, y: projectile.y, radius: 8, hp: 12, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return this.hp <= 0; } }; projectile.whirlwind.damageTimer = 0; const result = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [projectile] }); assert(enemy.hp === 9 && result.damageEvents.length === 1, "whirlwind area damage failed"); });
test("electric whirlwind aims and rearms after return", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-electric-whirlwind", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {}, activeWhirlwinds: new Map(), whirlwindCooldowns: new Map(), canFireWhirlwind(slotId) { return (this.whirlwindCooldowns.get(slotId) ?? 0) <= 0; } }; const enemy = { id: "right", x: 400, y: 450, hp: 10 }; const system = new WeaponSystem(); const projectile = system.firePlayer(player, [enemy])[0]; const slotId = [...player.activeWhirlwinds.keys()][0]; assert(projectile.vx > 0 && projectile.vy < 0, "whirlwind did not aim at nearest enemy"); projectile.x = 470; projectile.y = 300; projectile.update(0.01, [enemy], { width: 480, height: 854 }); assert(projectile.phase === 1, "whirlwind did not return from screen edge"); projectile.whirlwind.returnAge = 3.01; projectile.update(0.01, [enemy], { width: 480, height: 854 }); assert(Math.abs(Math.hypot(projectile.vx, projectile.vy) - 1800) < 0.001, "emergency return speed missing"); projectile.x = player.x; projectile.y = player.y - 24; projectile.update(0.01, [enemy], { width: 480, height: 854 }); assert(player.whirlwindCooldowns.get(slotId) === 0.6, "rearm delay missing"); });
test("skill cooldown ignores attack speed", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }, { moduleId: "special-optical", x: 5, y: 3 }, { moduleId: "special-energy-aggregator", x: 3, y: 4 }] }); const skills = new SkillSystem(loadout); const game = { state: "playing", createDecoy: (duration) => { game.duration = duration; }, player: { stats: { attackSpeed: 3 } } }; assert(skills.activate(0, game) && game.duration === 5 && skills.getState()[0].cooldownRemaining === 20 && !skills.activate(0, game), "skill cooldown was altered by attack speed"); });
test("multiple sonic skills stay independent", () => { const loadout = createLoadout({ modules: [{ moduleId: "special-sonic", x: 4, y: 3 }, { moduleId: "special-sonic", x: 4, y: 5 }] }); const skills = new SkillSystem(loadout); const game = { state: "playing", waveCalls: [], startSonicWave: (duration) => game.waveCalls.push(duration) }; assert(skills.getState().length === 2, "duplicate sonic skills were not preserved"); assert(skills.activate(0, game) && skills.activate(1, game), "sonic skills cannot be activated independently"); assert(game.waveCalls.length === 2 && !skills.activate(0, game) && !skills.activate(1, game), "sonic skill cooldowns are shared"); });
test("sonic wave interval and top cleanup", () => { const game = Object.create(Game.prototype); game.elapsed = 0; game.sonicWaves = [{ spawnTimer: 0, nextY: 0, step: 38 }]; game.lasers = []; game.updateSonicWave(0.01); assert(SONIC_WAVE_CONFIG.spawnInterval === 0.15, "sonic interval is not 0.15 seconds"); assert(game.sonicWaves.length === 0 && game.lasers.length === 1, "top beam sequence did not finish cleanly"); game.updateSonicWave(SONIC_WAVE_CONFIG.beamLife); assert(game.lasers.length === 1 && game.lasers[0].life === 0, "beam damage lifetime was not separated from visual afterglow"); game.updateSonicWave(SONIC_WAVE_CONFIG.beamVisualLife); assert(game.lasers.length === 0, "top beam visual afterglow was not removed"); });
test("disconnected modules are pruned", () => { const repaired = pruneDisconnected(createLoadout({ modules: [{ moduleId: "weapon-nest", x: 3, y: 4 }, { moduleId: "weapon-ricochet", x: 4, y: 2 }] })); assert(repaired.removed.some(({ moduleId }) => moduleId === "weapon-ricochet"), "disconnected module remains"); });
test("circle collision", () => { assert(circleIntersects({ x: 0, y: 0, radius: 10 }, { x: 15, y: 0, radius: 6 }), "circle hit"); assert(!circleIntersects({ x: 0, y: 0, radius: 5 }, { x: 20, y: 0, radius: 5 }), "circle miss"); });
test("circle rectangle collision", () => { assert(circleRectIntersects({ x: 12, y: 12, radius: 5 }, { x: 0, y: 0, width: 10, height: 10 }), "corner hit"); assert(!circleRectIntersects({ x: 30, y: 30, radius: 4 }, { x: 0, y: 0, width: 10, height: 10 }), "rectangle miss"); });
test("enemy contact damages player but never destroys the enemy", () => { const player = { x: 100, y: 100, radius: 12 }; const enemy = { id: "contact", x: 100, y: 100, radius: 12, hp: 5, definition: { score: 10 } }; const result = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [] }); assert(result.playerDamage === GAME_CONFIG.projectile.enemyContactDamage, "contact damage missing"); assert(!result.destroyedEnemies.has(enemy) && enemy.hp === 5, "contact collision destroyed or damaged the enemy"); });
test("player and enemy damage values", () => { assert(PLAYER_BASE_STATS.maxHp === 100, "core hp should be 100"); assert(GAME_CONFIG.projectile.enemyDamage === 5 && GAME_CONFIG.projectile.enemyContactDamage === 5, "enemy damage should be 5"); });
test("module rarity assignments", () => { const expected = { "weapon-electric-whirlwind": "legendary", "weapon-nest": "legendary", "weapon-lightning-generator": "legendary", "special-optical": "legendary", "special-sonic": "legendary", "special-zero": "legendary", "weapon-ball-lightning": "epic", "weapon-psionic": "epic", "special-wingman": "epic", "weapon-ricochet": "rare", "special-chainsaw": "rare", "special-energy-aggregator": "rare" }; for (const [id, rarity] of Object.entries(expected)) assert(getModuleById(id)?.rarity === rarity, `${id} rarity mismatch`); });

test("new module configuration", () => { const overclock = getModuleById("special-overclock"); const polarity = getModuleById("special-polarity-reverse"); const blackHole = getModuleById("weapon-black-hole"); assert(overclock?.footprint.cells.length === 4 && overclock.skill?.id === "overclock" && overclock.rarity === "legendary", "overclock configuration"); assert(polarity?.footprint.cells.length === 4 && polarity.skill?.id === "polarityReverse" && polarity.rarity === "legendary", "polarity configuration"); assert(blackHole?.footprint.cells.length === 4 && blackHole.behavior?.fireInterval === 7 && blackHole.behavior?.type === "blackHole" && blackHole.behavior.projectile.speed === 165 && blackHole.behavior.projectile.life === 3 && blackHole.behavior.projectile.damage === 0 && blackHole.behavior.projectile.blackHole.pullRadius === 66 && blackHole.behavior.projectile.blackHole.pullStrength === 210 && blackHole.behavior.projectile.blackHole.detonationDelay === 1 && blackHole.behavior.projectile.blackHole.explosionRadius === 37, "black hole configuration"); });
test("overclock refreshes without stacking", () => { const game = Object.create(Game.prototype); game.player = { overclockTimer: 1 }; game.startOverclock(5); assert(game.player.overclockTimer === 5, "overclock did not refresh to five seconds"); game.startOverclock(5); assert(game.player.overclockTimer === 5, "repeated overclock changed the duration or stacked it"); const player = { x: 240, y: 700, stats: { attackSpeed: 1 }, overclockTimer: 5, loadout: createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }, { moduleId: "special-overclock", x: 3, y: 3 }, { moduleId: "special-overclock", x: 5, y: 3 }] }), canFireWeapon: () => true, armWeapon(_id, interval) { this.interval = interval; } }; new WeaponSystem().firePlayer(player, []); assert(Math.abs(player.interval - 6 / 1.8) < 0.001, "multiple overclock modules stacked their attack speed"); });
test("black hole captures bullets and detonates their damage", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-black-hole", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const hole = new WeaponSystem().firePlayer(player, [])[0]; const enemyBolt = new Projectile({ x: hole.x + 40, y: hole.y, vx: 0, vy: 80, damage: 6, radius: 4, color: "#ff557c", life: 3, team: "enemy" }); const game = Object.create(Game.prototype); game.projectiles = [hole, enemyBolt]; game.enemies = []; game.applyBlackHolePull(0.1); assert(enemyBolt.blackHoleCapturedBy === hole && hole.blackHole.capturedProjectiles.has(enemyBolt) && enemyBolt.blackHoleOrbit.radius > 0 && enemyBolt.blackHoleOrbit.radius < hole.blackHole.pullRadius && !hole.blackHole.slowed, "black hole capture orbit state"); const enemy = { id: "detonation-target", x: hole.x, y: hole.y, radius: 10, hp: 20, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return false; } }; hole.life = 0; const result = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [hole, enemyBolt] }); assert(enemy.hp === 14 && result.removedProjectiles.has(enemyBolt) && result.explosionEvents[0].kind === "blackHole" && result.explosionEvents[0].capturedCount === 1, "captured bullet did not detonate"); });
test("black hole detonates one second after capturing an enemy", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-black-hole", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const hole = new WeaponSystem().firePlayer(player, [])[0]; const enemy = { id: "captured-enemy", x: hole.x, y: hole.y + 20, hp: 10 }; const game = Object.create(Game.prototype); game.projectiles = [hole]; game.enemies = [enemy]; game.applyBlackHolePull(0.1); assert(hole.blackHole.enemyCaptured && Math.abs(hole.blackHole.detonationTimer - 0.9) < 0.001, "enemy capture did not start one-second detonation timer"); game.applyBlackHolePull(0.9); assert(hole.life <= 0, "black hole did not detonate after one second"); });
const failed = results.filter((line) => line.startsWith("FAIL")).length; output.className = failed ? "fail" : "pass"; output.textContent = `${failed ? "Some tests failed" : "All tests passed"}\n\n${results.join("\n")}`;
