import { ASSEMBLY_BOARD, MODULE_CONFIG, CORE_MODULE, PLAYER_DISABLED_MODULE_IDS, createLoadout as createRawLoadout, getFootprintCells, getInstalledEntries, getModuleById, getModuleElement } from "../src/config/module-config.js";
import { MAX_SKILL_MODULES, calculateFinalStats, countSkillModules, pruneDisconnected, validateLoadout } from "../src/systems/ModuleSystem.js";
import { CollisionSystem, circleIntersects, circleRectIntersects } from "../src/systems/CollisionSystem.js";
import { WeaponSystem } from "../src/systems/WeaponSystem.js";
import { SkillSystem } from "../src/systems/SkillSystem.js";
import { decodeLoadoutCode, encodeLoadoutCode } from "../src/systems/LoadoutCodec.js";
import { GAME_CONFIG, PLAYER_BASE_STATS, SONIC_WAVE_CONFIG } from "../src/config/game-config.js";
import { ENEMY_CONFIG, UNRELEASED_ENEMY_CONFIG, createBossDefinition, getEnemyById } from "../src/config/enemy-config.js";
import { getEncyclopediaSections, getUnreleasedEnemyArchiveEntries } from "../src/config/encyclopedia-config.js";
import { LEVELS } from "../src/config/level-config.js";
import { getEnvironmentPool } from "../src/config/environment-config.js";
import { DODGE_DIFFICULTIES, getDodgeDifficulty } from "../src/config/dodge-config.js";
import { getSynergyStates, hasActiveSynergy, normalizeSynergies } from "../src/config/synergy-config.js";
import { BEYOND_EVENTS } from "../src/config/beyond-events-config.js";
import { getBeyondChapterCount } from "../src/config/beyond-light-cone-config.js";
import { BeyondLightConeSystem } from "../src/systems/BeyondLightConeSystem.js";
import { Player } from "../src/entities/Player.js"; import { Enemy } from "../src/entities/Enemy.js"; import { Projectile } from "../src/entities/Projectile.js"; import { Wingman } from "../src/entities/Wingman.js"; import "../src/entities/Decoy.js"; import { Game } from "../src/core/Game.js";

// Keep the older fixture layouts centered when the production board grows from 9x9 to 15x15.
const createLoadout = (spec = {}) => createRawLoadout({ ...spec, modules: (spec.modules ?? []).map((entry) => ({ ...entry, x: entry.x == null ? entry.x : entry.x + 3, y: entry.y == null ? entry.y : entry.y + 3 })) });

const output = document.querySelector("#test-output"); const results = [];
function assert(condition, message) { if (!condition) throw new Error(message); }
function test(name, callback) { try { callback(); results.push(`PASS ${name}`); } catch (error) { results.push(`FAIL ${name}\n  ${error.message}`); } }

test("enemy base health values", () => { const hp = Object.fromEntries(ENEMY_CONFIG.map((enemy) => [enemy.type, enemy.hp])); assert(hp.scout === 5 && hp.swift === 5 && hp.guardian === 20, "enemy base health values are incorrect"); });
test("basic enemy shots fire straight downward", () => { const player = { x: 420, y: 700 }; const system = new WeaponSystem(); for (const type of ["scout", "swift", "guardian"]) { const definition = ENEMY_CONFIG.find((enemy) => enemy.type === type); const enemy = new Enemy(definition, 120, { spawnY: 100 }); const shot = system.fireEnemy(enemy, player); assert(!Array.isArray(shot) && Math.abs(shot.vx) < 0.001 && shot.vy > 0, `${type} did not fire straight downward`); } });
test("prototype enemy archive stays distinct and listed in the merged encyclopedia", () => { const ids = UNRELEASED_ENEMY_CONFIG.map((enemy) => enemy.id); const types = UNRELEASED_ENEMY_CONFIG.map((enemy) => enemy.type); const archive = getUnreleasedEnemyArchiveEntries(); const enemySection = getEncyclopediaSections().find((section) => section.title === "敌机档案"); const listedTitles = new Set(enemySection?.entries.map((entry) => entry.title) ?? []); const visualTypes = Object.fromEntries(archive.map((entry) => [entry.title, entry.enemyVisual.type])); const flippedNames = ["彗尾信使", "钟摆信标", "缎带鳐", "绽放的花蕾"]; assert(UNRELEASED_ENEMY_CONFIG.length === 10 && new Set(ids).size === 10 && new Set(types).size === 10, "unreleased enemy prototypes are incomplete or duplicated"); assert(UNRELEASED_ENEMY_CONFIG.every((enemy) => !ENEMY_CONFIG.includes(enemy) && getEnemyById(enemy.id) === null), "unreleased enemies leaked into active spawn definitions"); assert(visualTypes["彗尾信使"] === "comet" && visualTypes["钟摆信标"] === "pendulum" && visualTypes["缎带鳐"] === "ribbon" && visualTypes["绽放的花蕾"] === "petal", "unreleased enemy visual mapping is incorrect"); assert(flippedNames.every((name) => archive.find((entry) => entry.title === name)?.enemyVisual.flipY === true), "target enemy encyclopedia drawings are not vertically flipped"); assert(archive.length === 10 && archive.every((entry) => entry.enemyVisual && entry.description.length > 0 && listedTitles.has(entry.title)) && enemySection, "prototype enemies are missing from the merged encyclopedia archive"); });
test("100 level campaign and boss schedule", () => { assert(LEVELS.length === 100, "level count"); assert(Array.from({ length: 20 }, (_, index) => (index + 1) * 5).every((number) => LEVELS[number - 1].boss), "boss schedule"); assert(LEVELS[99].hpMultiplier > LEVELS[0].hpMultiplier && LEVELS[99].enemyPool.length > LEVELS[0].enemyPool.length, "difficulty did not grow"); const boss = createBossDefinition(100); const variantIds = ["storm-warden", "nest-matriarch", "prism-oracle", "zero-archon", "lattice-leviathan", "abyss-gardener", "chorus-conductor", "cryo-hive-queen"]; const variants = variantIds.map((id) => createBossDefinition(20, id)); assert(boss.boss && boss.hp > createBossDefinition(5).hp && boss.bossSkills.includes("radial"), "boss scaling"); assert(variants.every((item) => item.boss && item.bossShape && item.attackPattern) && new Set(variants.map((item) => item.bossShape)).size === variantIds.length && new Set(variants.map((item) => item.attackPattern)).size >= 5, "boss variants are not visually or mechanically distinct"); });
test("encyclopedia lists every boss variant", () => { const bossSection = getEncyclopediaSections().find((section) => section.title === "首领机制"); const titles = bossSection.entries.map((entry) => entry.title); assert(["雷暴监守", "覆巢母舰", "棱镜先知", "零度执政官", "晶格利维坦", "深渊园丁", "合唱指挥舰", "寒潮蜂后"].every((name) => titles.includes(name)), "boss variant encyclopedia entries are incomplete"); });
test("beyond event archive provides rare legendary encounters", () => { const system = new BeyondLightConeSystem(); const run = system.createRun(1, "event-test-seed"); const node = { id: "event-test", type: "event" }; const ids = BEYOND_EVENTS.map((event) => event.id); assert(BEYOND_EVENTS.length === 34 && new Set(ids).size === 34 && BEYOND_EVENTS.filter((event) => event.rareLegendary).length === 4 && BEYOND_EVENTS.every((event) => event.choices.length >= 2), "event archive is incomplete"); const encounter = system.createEventEncounter(run, node); const selectedChoice = encounter.choices.find((choice) => choice.available); const result = system.resolveEventChoice(run, node, encounter.event.id, selectedChoice?.id); assert(run.eventHistory.includes(encounter.event.id) && !run.activeEvent && result.event.id === encounter.event.id, "event result did not persist correctly"); });
test("dormant fusion definitions keep exact recipes without exposing disabled modules", () => { const system = new BeyondLightConeSystem(); const run = system.createRun(1, "fusion-test-seed"); run.inventory["weapon-water-shot"] = 1; run.inventory["weapon-ball-lightning"] = 1; run.inventory["weapon-flame-crossbow"] = 1; const slots = Array(9).fill(null); slots[3] = "weapon-water-shot"; slots[4] = "weapon-ball-lightning"; slots[5] = "weapon-flame-crossbow"; const product = system.synthesize(run, slots).product; assert(product.id === "fusion-cryo-hive" && run.inventory[product.id] === 1, "translated fusion recipe did not resolve"); const returned = system.decompose(run, product.id); assert(returned.returned.length === 3 && run.inventory[product.id] === 0 && run.inventory["weapon-water-shot"] === 1, "fusion decomposition did not restore materials"); assert(system.getBeyondRewardModules().every((module) => !PLAYER_DISABLED_MODULE_IDS.has(module.id)), "disabled modules leaked into the reward pool"); const bossNode = run.map.at(-1)[0]; const bossReward = system.rewardModules(run, 1, { boss: true }); assert(bossReward.length === 1 && getModuleById(bossReward[0])?.rarity === "legendary" && bossReward[0] === bossNode.bossRewardId, "boss did not grant its fixed legendary module"); });
test("beyond chapter flow keeps resources and scales later chapters", () => { const system = new BeyondLightConeSystem(); assert(getBeyondChapterCount(1) === 1 && getBeyondChapterCount(2) === 2 && getBeyondChapterCount(3) === 3 && getBeyondChapterCount(4) === 3, "chapter counts are incorrect"); const run = system.createRun(3, "chapter-test-seed"); run.inventory["weapon-nest"] = 2; run.gold = 77; run.hp = 41; const firstMapSeed = run.chapterSeed; const firstBoss = run.map.at(-1)[0]; const firstConfig = system.getBattleConfig(run, firstBoss); assert(run.chapter === 1 && run.totalChapters === 3, "multi-chapter run did not initialize"); assert(system.advanceChapter(run) && run.chapter === 2 && run.currentNodeId === null && run.visited.length === 0, "chapter did not advance"); const secondConfig = system.getBattleConfig(run, run.map.at(-1)[0]); assert(run.chapterSeed !== firstMapSeed && run.inventory["weapon-nest"] === 2 && run.gold === 77 && run.hp === 41 && secondConfig.hpMultiplier > firstConfig.hpMultiplier, "chapter transition lost resources or did not scale difficulty"); });
test("beyond first chapter opens with three mandatory event nodes", () => { const system = new BeyondLightConeSystem(); const run = system.createRun(1, "opening-event-seed"); const opening = run.map.slice(0, 3).map((layer) => layer[0]); assert(opening.length === 3 && run.map.slice(0, 3).every((layer) => layer.length === 1) && opening.every((node) => node.type === "event") && opening.map((node) => node.eventId).join(",") === "orphan-wingman,zero-maintenance,gravity-post", "opening route is not three sequential events"); let available = system.getAvailableNodes(run); for (const node of opening) { assert(available.length === 1 && available[0].id === node.id, "opening event is not mandatory"); system.enterNode(run, node.id); available = system.getAvailableNodes(run); } assert(available.length > 0 && available.every((node) => node.layer === 3), "normal route did not begin after the third event"); });
test("special environments unlock after level 25", () => { assert(LEVELS[24].environmentPool.length === 0 && !LEVELS[24].environment, "environment unlocked too early"); assert(LEVELS[25].environmentPool.length > 0 && LEVELS[25].environment, "environment missing from level 26"); assert(getEnvironmentPool(50).length >= 4, "late environments missing"); });
test("dodge mode difficulty and hazard generation", () => { assert(DODGE_DIFFICULTIES.length === 3 && getDodgeDifficulty("nightmare").speed > getDodgeDifficulty("easy").speed, "dodge difficulties are incomplete"); const game = Object.create(Game.prototype); game.bounds = { width: 480, height: 854 }; game.dodgeDifficulty = getDodgeDifficulty("hard"); game.elapsed = 0; game.dodgePatternIndex = 0; game.projectiles = []; game.spawnDodgePattern(); assert(game.projectiles.length > 0 && game.projectiles.every((projectile) => projectile.team === "enemy" && projectile.dodgeBullet), "dodge mode did not create hazard projectiles"); });

test("dodge mode can spawn hazards in the lower half", () => { const game = Object.create(Game.prototype); game.bounds = { width: 480, height: 854 }; game.dodgeDifficulty = { ...getDodgeDifficulty("easy"), patternPool: [10] }; game.elapsed = 0; game.dodgePatternIndex = 0; game.dodgePatternHistory = -1; game.projectiles = []; game.spawnDodgePattern(); assert(game.projectiles.length > 0 && game.projectiles.some((projectile) => projectile.y > game.bounds.height * 0.5 && projectile.vy < 0), "dodge mode lower-half pattern is missing"); });
test("boss summon configuration and wave", () => { const boss = createBossDefinition(25); assert(boss.summon.interval < createBossDefinition(5).summon.interval && boss.summon.count === 2, "boss summon scaling"); const game = Object.create(Game.prototype); game.boss = { x: 240, y: 120, hp: 100, definition: boss }; game.bossSummonTimer = 0; game.bossSummonCount = 0; game.enemies = [game.boss]; game.levelNumber = 25; game.levelConfig = { hpMultiplier: 1.5, speedMultiplier: 1.2 }; game.bounds = { width: 480, height: 854 }; const minions = game.updateBossSummons(0.1); assert(minions.length === 2 && minions.every((enemy) => enemy.summoned && !enemy.boss), "boss did not summon minions"); game.enemies.push(...minions); game.bossSummonTimer = 0; assert(game.updateBossSummons(0.1).length === 2, "boss summon cooldown or cap incorrect"); });
test("skill modules keep nine-module limit while regular total limit is removed", () => { const modules = [{ moduleId: "special-chainsaw", x: 4, y: 3 }, { moduleId: "special-chainsaw", x: 2, y: 3 }, { moduleId: "special-chainsaw", x: 0, y: 3 }, { moduleId: "special-chainsaw", x: -2, y: 3 }, { moduleId: "special-chainsaw", x: 6, y: 3 }, { moduleId: "special-chainsaw", x: 8, y: 3 }, { moduleId: "special-chainsaw", x: 10, y: 3 }, { moduleId: "special-chainsaw", x: 4, y: 5 }, { moduleId: "special-chainsaw", x: 2, y: 5 }, { moduleId: "special-chainsaw", x: 0, y: 5 }]; const manySkills = createLoadout({ modules }); assert(MAX_SKILL_MODULES === 9 && countSkillModules(manySkills) === 10 && !validateLoadout(manySkills).valid, "tenth skill module should be rejected"); });

test("15x15 board and centered core", () => { assert(ASSEMBLY_BOARD.columns === 15 && ASSEMBLY_BOARD.rows === 15, "board size"); assert(ASSEMBLY_BOARD.corePosition.x === 7 && ASSEMBLY_BOARD.corePosition.y === 7 && CORE_MODULE.type === "core", "core position"); });
test("large regular loadout remains valid", () => { const modules = []; for (let y = 0; y < ASSEMBLY_BOARD.rows && modules.length < 120; y += 1) for (let x = 0; x < ASSEMBLY_BOARD.columns && modules.length < 120; x += 1) if (x !== ASSEMBLY_BOARD.corePosition.x || y !== ASSEMBLY_BOARD.corePosition.y) modules.push({ moduleId: "weapon-ricochet", x, y }); const loadout = createRawLoadout({ modules }); const result = validateLoadout(loadout); assert(result.valid && loadout.modules.length === 120, `large loadout rejected: ${result.reason}`); });
test("large regular loadout initializes combat entities", () => { const modules = []; for (let y = 0; y < ASSEMBLY_BOARD.rows && modules.length < 120; y += 1) for (let x = 0; x < ASSEMBLY_BOARD.columns && modules.length < 120; x += 1) if (x !== ASSEMBLY_BOARD.corePosition.x || y !== ASSEMBLY_BOARD.corePosition.y) modules.push({ moduleId: "weapon-ricochet", x, y }); const loadout = createRawLoadout({ modules }); const player = new Player({ x: 240, y: 700, stats: calculateFinalStats(PLAYER_BASE_STATS, getInstalledEntries(loadout).map(({ module }) => module)), loadout }); const shots = new WeaponSystem().firePlayer(player, []); assert(player.installedEntries.length === 121 && shots.length > 0 && player.weaponEntries.length === 120, "large loadout combat initialization failed"); });
test("multi-cell electric whirlwind loadout", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-nest", x: 1, y: 4 }, { moduleId: "weapon-electric-whirlwind", x: 3, y: 3 }] }); assert(validateLoadout(loadout).valid, "connected loadout"); const cells = getModuleById("weapon-electric-whirlwind").footprint.cells; assert(cells.length === 3 && cells.every(([x]) => x === 0), "vertical three-cell footprint"); });
test("stats merge", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }, { moduleId: "special-wingman", x: 3, y: 4 }] }); const stats = calculateFinalStats(PLAYER_BASE_STATS, getInstalledEntries(loadout).map(({ module }) => module)); assert(stats.maxHp === PLAYER_BASE_STATS.maxHp && stats.moveSpeed === PLAYER_BASE_STATS.moveSpeed && stats.attackSpeed === PLAYER_BASE_STATS.attackSpeed, "base stats changed"); });
test("wolfpack synergy validates exclusive module pairing", () => {
  const base = createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }, { moduleId: "special-wingman", x: 4, y: 2 }] });
  const [nest, wingman] = base.modules;
  const selected = { ...base, synergies: [{ id: "synergy-wolfpack", moduleInstanceIds: [nest.instanceId, wingman.instanceId] }] };
  const duplicated = { ...selected, synergies: [...selected.synergies, { id: "synergy-wolfpack", moduleInstanceIds: [nest.instanceId, wingman.instanceId] }] };
  assert(validateLoadout(selected).valid && hasActiveSynergy(selected, "synergy-wolfpack"), "wolfpack selection is invalid");
  assert(normalizeSynergies(duplicated).length === 1 && getSynergyStates(selected)[0].activeSelections.length === 1, "occupied modules were reused by another synergy");
});
test("wolfpack wingman keeps its bolt and adds nest volley", () => {
  const wingman = new Wingman({ x: 240, y: 700, stats: { attackSpeed: 1 } }, { wolfpack: true }); wingman.nestTimer = 0;
  const system = new WeaponSystem(); const bolt = wingman.fire(); const volley = system.fireWingmanNest(wingman, [{ id: "target", x: 240, y: 280, hp: 10 }]);
  assert(bolt?.kind === "bolt" && volley.length === 6 && volley.every((shot) => shot.kind === "nestMissile" && shot.damage === 5), "wolfpack did not add an independent nest volley");
});
test("water-fire synergy swaps attacks with the requested probabilities", () => {
  const loadout = createLoadout({ modules: [{ instanceId: "flame-1", moduleId: "weapon-flame-crossbow", x: 7, y: 6 }, { instanceId: "water-1", moduleId: "weapon-water-shot", x: 6, y: 7 }], synergies: [{ id: "synergy-water-fire", moduleInstanceIds: ["water-1", "flame-1"] }] });
  assert(hasActiveSynergy(loadout, "synergy-water-fire"), "water-fire synergy is not active");
  const player = new Player({ x: 240, y: 700, stats: calculateFinalStats(PLAYER_BASE_STATS, getInstalledEntries(loadout).map(({ module }) => module)), loadout });
  const originalRandom = Math.random;
  try {
    player.weaponTimers.forEach((_, key) => player.weaponTimers.set(key, 0));
    let rolls = [0.2, 0.9]; Math.random = () => rolls.shift() ?? 0.9;
    const waterSwap = new WeaponSystem().firePlayer(player, []);
    assert(waterSwap.filter((shot) => shot.kind === "waterShot").length === 4 && waterSwap.every((shot) => shot.element === "water"), "flame attack did not convert to three water shots");
    player.weaponTimers.forEach((_, key) => player.weaponTimers.set(key, 0));
    rolls = [0.9, 0.2];
    const fireSwap = new WeaponSystem().firePlayer(player, []);
    assert(fireSwap.filter((shot) => shot.kind === "flameArrow").length === 3 && fireSwap.filter((shot) => shot.kind === "waterShot" && shot.element === "fire").length === 1 && fireSwap.some((shot) => shot.kind === "waterShot" && shot.burn?.ticks === 9 && shot.color === "#ff3344"), "water attack did not convert to a red burning water shot");
  } finally { Math.random = originalRandom; }
});
test("white hole takes over captured bullets and caps healing", () => {
  const game = Object.create(Game.prototype); const player = { x: 240, y: 700 }; game.player = player; game.projectiles = []; game.whiteHoleActive = true;
  const hole = new Projectile({ x: 240, y: 400, damage: 0, radius: 8, color: "#b57bff", life: 2, team: "player", kind: "blackHole", blackHole: { capturedProjectiles: new Set() } });
  const captured = new Projectile({ x: 250, y: 400, vx: 0, vy: 0, damage: 7, radius: 5, color: "#ff557c", life: 3, team: "enemy" });
  captured.blackHoleCapturedBy = hole; hole.blackHole.capturedProjectiles.add(captured); game.projectiles = [hole, captured];
  game.startPolarityReverse(0.25); assert(!captured.blackHoleCapturedBy && captured.whiteHoleCandidate && captured.polarityDelay === 0.25, "captured bullet was not released");
  captured.polarityDelay = 0; game.convertPolarityProjectile(captured); assert(captured.team === "player" && captured.homingPlayer && captured.pierce && captured.whiteHoleHealState.remaining === 30, "white hole projectile conversion failed");
  const target = { id: "white-hole-target", x: captured.x, y: captured.y, radius: 8, hp: 20, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return false; } };
  const hit = new CollisionSystem().resolve({ player: { x: 0, y: 0, radius: 10 }, enemies: [target], projectiles: [captured] }); assert(target.hp === 13 && !hit.removedProjectiles.has(captured), "white hole bullet did not pierce enemy");
  captured.x = 0; captured.y = 0; const heal = new CollisionSystem().resolve({ player: { x: 0, y: 0, radius: 10 }, enemies: [], projectiles: [captured] }); assert(heal.playerHealing === 7 && heal.playerDamage === 0, "white hole bullet did not heal player");
});
test("energy aggregator adds attack speed and is an automatic module", () => { const aggregator = getModuleById("special-energy-aggregator"); const boosted = calculateFinalStats(PLAYER_BASE_STATS, [aggregator, aggregator]); const capped = calculateFinalStats(PLAYER_BASE_STATS, Array.from({ length: 12 }, () => aggregator)); assert(MODULE_CONFIG.weapons.includes(aggregator) && !MODULE_CONFIG.specials.includes(aggregator) && aggregator.type === "weapon" && !aggregator.skill && aggregator.footprint.cells.length === 1 && aggregator.shareCode === 12, "aggregator category configuration missing"); assert(boosted.attackSpeed === 1.4 && capped.attackSpeed === GAME_CONFIG.player.maxAttackSpeed, `invalid attack speed: ${boosted.attackSpeed}/${capped.attackSpeed}`); });
test("automatic fire interval follows attack speed", () => { const player = { x: 240, y: 700, stats: { attackSpeed: 1.2 }, loadout: createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon(_id, interval) { this.interval = interval; } }; new WeaponSystem().firePlayer(player, []); const wingman = new Wingman({ x: 240, y: 700, stats: { attackSpeed: 2 } }); wingman.fire(); assert(Math.abs(player.interval - 5) < 0.001 && Math.abs(wingman.fireTimer - 1 / 6) < 0.001, `automatic intervals did not scale: ${player.interval}/${wingman.fireTimer}`); });
test("combat module is optional", () => { const loadout = createLoadout({ modules: [] }); assert(validateLoadout(loadout).valid, "empty loadout should enter battle"); });
test("loadout code round trip", () => { const source = createLoadout({ modules: [{ moduleId: "weapon-electric-whirlwind", x: 3, y: 3 }, { moduleId: "special-optical", x: 5, y: 4, rotation: 1 }] }); const code = encodeLoadoutCode(source); const restored = decodeLoadoutCode(code).loadout; const signature = (loadout) => loadout.modules.map(({ moduleId, x, y, rotation }) => `${moduleId}:${x}:${y}:${rotation}`).sort().join("|"); assert(code.startsWith("!1") && !code.includes("weapon") && !code.includes("special"), "code exposes module ids"); assert(signature(restored) === signature(source), "loadout was not restored exactly"); });
test("loadout code validates checksum and module codes", () => { const codes = [...MODULE_CONFIG.weapons, ...MODULE_CONFIG.specials].map((module) => module.shareCode); assert(new Set(codes).size === codes.length && codes.every((code) => Number.isInteger(code) && code > 0), "module share codes are not stable and unique"); const code = encodeLoadoutCode(createLoadout({ modules: [{ moduleId: "weapon-electric-whirlwind", x: 3, y: 3 }] })); const last = code.at(-1); const corrupted = `${code.slice(0, -1)}${last === "0" ? "1" : "0"}`; let rejected = false; try { decodeLoadoutCode(corrupted); } catch { rejected = true; } assert(rejected, "corrupted code was accepted"); });
test("player invulnerability after damage", () => { const player = new Player({ x: 240, y: 700, stats: PLAYER_BASE_STATS, loadout: createLoadout({ modules: [] }) }); player.damage(5); assert(player.hp === 95 && player.invulnerabilityTimer === 1, "first damage was not applied"); player.damage(5); assert(player.hp === 95, "damage applied during invulnerability"); player.update(1.01, { pointer: { active: false }, getMovementVector: () => ({ x: 0, y: 0 }) }, GAME_CONFIG.canvas); player.damage(5); assert(player.hp === 90 && player.invulnerabilityTimer === 1, "damage did not return after invulnerability"); });
test("current weapon configuration", () => { assert(MODULE_CONFIG.weapons.length === 14 && ["weapon-obsidian-beam", "weapon-eclipse-pulse", "weapon-fire-feather", "fusion-polar-saw"].every((id) => MODULE_CONFIG.weapons.some((module) => module.id === id)), "current weapon count or v0.7 entries"); assert(["weapon-single", "weapon-twin", "weapon-spread", "weapon-missile", "weapon-boomerang"].every((id) => !getModuleById(id)), "removed weapon modules remain"); const nest = getModuleById("weapon-nest"); assert(nest.behavior.projectile.color === "#ef294d" && nest.behavior.projectile.speed === 580 && nest.behavior.projectile.radius === 18 && nest.behavior.projectile.explosionRadius === 72 && nest.behavior.projectile.homingDelay === 0.42 && nest.behavior.spreadAngle === 0.18, "nest tuning"); assert(getModuleById("weapon-ball-lightning").behavior.projectile.radius === 12 && getModuleById("weapon-ball-lightning").behavior.projectile.growthRate === 8.8, "ball lightning size"); const whirlwind = getModuleById("weapon-electric-whirlwind"); assert(whirlwind.footprint.cells.length === 3 && whirlwind.footprint.cells.every(([x]) => x === 0) && whirlwind.behavior.projectile.damage === 2 && whirlwind.behavior.projectile.radius === 76 && whirlwind.behavior.projectile.speed === 520 && whirlwind.behavior.projectile.returnTimeout === 3 && whirlwind.behavior.projectile.emergencyReturnSpeed === 1800 && whirlwind.behavior.projectile.rearmDelay === 0.6 && whirlwind.behavior.damageInterval === 0.1, "whirlwind tuning"); const lightning = getModuleById("weapon-lightning-generator"); assert(lightning.footprint.cells.length === 2 && lightning.behavior.fireRate === 0.5 && lightning.behavior.fireInterval === 2 && lightning.behavior.projectile.damage === 7 && lightning.behavior.projectile.chainRadius === 200 && lightning.behavior.projectile.chainLife === 0.25 && lightning.behavior.projectile.flashDuration === 0.045, "lightning generator tuning"); const flame = getModuleById("weapon-flame-crossbow"); assert(flame.rarity === "epic" && flame.element === "fire" && flame.behavior.fireInterval === 1.5 && flame.behavior.angles.length === 3 && flame.behavior.projectile.damage === 5 && flame.behavior.projectile.burn.duration === 3 && flame.behavior.projectile.burn.tickInterval === 1 / 3 && flame.behavior.projectile.burn.ticks === 9, "flame crossbow configuration"); const water = getModuleById("weapon-water-shot"); assert(water.rarity === "epic" && water.element === "water" && water.behavior.fireRate === 5 && water.behavior.projectile.explosionDamage === 2 && water.behavior.projectile.explosionRadius > 0, "water shot configuration"); });
test("updated special module footprints", () => { const zero = getModuleById("special-zero"); const wingman = getModuleById("special-wingman"); assert(zero.footprint.cells.length === 3 && zero.footprint.cells.every(([, y]) => y === 0), "zero domain is horizontal three-cell"); assert(wingman.footprint.cells.length === 3 && wingman.footprint.cells.every(([, y]) => y === 0), "wingman is horizontal three-cell"); });

test("nest missiles spread before homing", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const makeEnemy = (id, x) => ({ id, x, y: 240, hp: 10 }); const enemies = [makeEnemy("left", 80), makeEnemy("mid", 240), makeEnemy("right", 400)]; const missiles = new WeaponSystem().firePlayer(player, enemies); assert(new Set(missiles.map((missile) => missile.target?.id)).size === 3, "nest targets are not distributed"); const initialVx = missiles.map((missile) => missile.vx); missiles[0].update(0.2, enemies); assert(missiles[0].vx === initialVx[0], "nest homed before spread delay"); missiles[0].update(0.3, enemies); assert(missiles[0].vx !== initialVx[0], "nest did not start homing after delay"); });
test("nest missile creates visible explosion event", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const projectile = new WeaponSystem().firePlayer(player, [])[0]; const enemy = { id: "target", x: projectile.x, y: projectile.y, radius: 10, hp: 10, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return this.hp <= 0; } }; const result = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [projectile] }); assert(projectile.kind === "nestMissile" && Math.abs(Math.hypot(projectile.vx, projectile.vy) - 580) < 0.001 && result.explosionEvents.length === 1 && result.explosionEvents[0].radius === 72, `nest explosion event missing: kind=${projectile.kind}, speed=${Math.hypot(projectile.vx, projectile.vy)}, radius=${projectile.explosionRadius}, events=${result.explosionEvents.length}`); });
test("lightning generator chains unique nearby targets", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-lightning-generator", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const makeEnemy = (id, x, y) => ({ id, x, y, radius: 8, hp: 10, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return this.hp <= 0; } }); const enemies = [makeEnemy("front", 240, 500), makeEnemy("near", 240, 570), makeEnemy("far", 400, 570), makeEnemy("offscreen", 500, 570), makeEnemy("back", 240, 820)]; const projectile = new WeaponSystem().firePlayer(player, enemies)[0]; assert(projectile.kind === "chainLightning" && projectile.target.id === "near" && projectile.chainRadius === 200 && projectile.life === 0.25, "lightning target or lifetime incorrect"); const result = new CollisionSystem().resolve({ player, enemies, projectiles: [projectile] }); assert(result.damageEvents.length === 3 && enemies.filter((enemy) => enemy.hp === 3).length === 3 && enemies[3].hp === 10 && enemies[4].hp === 10, "lightning chain did not hit only visible unique targets"); });
test("weapon origin follows module", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-ricochet", x: 5, y: 4 }] }); const player = { x: 100, y: 200, loadout, canFireWeapon: () => true, armWeapon: () => {} }; const projectile = new WeaponSystem().firePlayer(player, [])[0]; assert(projectile.x === 113 && projectile.y === 192, "origin incorrect"); });
test("electric whirlwind returns and deals area damage", () => { const player = { x: 100, y: 300, loadout: createLoadout({ modules: [{ moduleId: "weapon-electric-whirlwind", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const projectile = new WeaponSystem().firePlayer(player, [])[0]; assert(projectile.kind === "electricWhirlwind" && projectile.whirlwind && projectile.vy < 0, "whirlwind did not launch upward"); projectile.y = 20; projectile.update(0.01, []); assert(projectile.phase === 1, "whirlwind did not turn at top"); const enemy = { id: "near", x: projectile.x + 15, y: projectile.y, radius: 8, hp: 12, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return this.hp <= 0; } }; projectile.whirlwind.damageTimer = 0; const result = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [projectile] }); assert(enemy.hp === 10 && result.damageEvents.length === 1, "whirlwind area damage failed"); });
test("ion saw uses a wide dual-side high-frequency damage zone", () => { const player = { x: 240, y: 700, radius: 12 }; const makeEnemy = (id, x, y) => ({ id, x, y, radius: 8, hp: 20, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return this.hp <= 0; } }); const left = makeEnemy("left", 198, 700); const right = makeEnemy("right", 282, 700); const outside = makeEnemy("outside", 240, 660); const ionSaw = { active: true, damage: 2, damageTimer: 0, damageInterval: 0.12, reach: 42, radius: 26 }; const first = new CollisionSystem().resolve({ player, enemies: [left, right, outside], projectiles: [], ionSaw }); assert(first.sawTriggered && first.sawHitCount === 2 && left.hp === 18 && right.hp === 18 && outside.hp === 20 && first.destroyedEnemies.size === 0, "ion saw did not apply normal dual-side damage"); ionSaw.damageTimer = ionSaw.damageInterval; const second = new CollisionSystem().resolve({ player, enemies: [left, right, outside], projectiles: [], ionSaw }); assert(second.sawHitCount === 0 && left.hp === 18 && right.hp === 18, "ion saw ignored its damage interval"); });
test("ion saw cuts enemy projectiles", () => { const player = { x: 240, y: 700, radius: 12 }; const makeProjectile = (x, y) => new Projectile({ x, y, vx: 0, vy: 100, damage: 5, radius: 5, color: "#ff638c", life: 2, team: "enemy", kind: "enemyBolt" }); const left = makeProjectile(198, 700); const right = makeProjectile(282, 700); const outside = makeProjectile(240, 660); const ionSaw = { active: true, damage: 2, damageTimer: 0, damageInterval: 0.12, reach: 42, radius: 26 }; const result = new CollisionSystem().resolve({ player, enemies: [], projectiles: [left, right, outside], ionSaw }); assert(result.sawTriggered && result.sawProjectileCount === 2 && result.removedProjectiles.has(left) && result.removedProjectiles.has(right) && !result.removedProjectiles.has(outside), "ion saw did not cut enemy projectiles"); });
test("electric whirlwind aims and rearms after return", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-electric-whirlwind", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {}, activeWhirlwinds: new Map(), whirlwindCooldowns: new Map(), canFireWhirlwind(slotId) { return (this.whirlwindCooldowns.get(slotId) ?? 0) <= 0; } }; const enemy = { id: "right", x: 400, y: 450, hp: 10 }; const system = new WeaponSystem(); const projectile = system.firePlayer(player, [enemy])[0]; const slotId = [...player.activeWhirlwinds.keys()][0]; assert(projectile.vx > 0 && projectile.vy < 0, "whirlwind did not aim at nearest enemy"); projectile.x = 470; projectile.y = 300; projectile.update(0.01, [enemy], { width: 480, height: 854 }); assert(projectile.phase === 1, "whirlwind did not return from screen edge"); projectile.whirlwind.returnAge = 3.01; projectile.update(0.01, [enemy], { width: 480, height: 854 }); assert(Math.abs(Math.hypot(projectile.vx, projectile.vy) - 1800) < 0.001, "emergency return speed missing"); projectile.x = player.x; projectile.y = player.y - 24; projectile.update(0.01, [enemy], { width: 480, height: 854 }); assert(player.whirlwindCooldowns.get(slotId) === 0.6, "rearm delay missing"); });
test("skill cooldown ignores attack speed", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }, { moduleId: "special-optical", x: 5, y: 3 }, { moduleId: "special-energy-aggregator", x: 3, y: 4 }] }); const skills = new SkillSystem(loadout); const game = { state: "playing", createDecoy: (duration) => { game.duration = duration; }, player: { stats: { attackSpeed: 3 } } }; assert(skills.activate(0, game) && game.duration === 5 && skills.getState()[0].cooldownRemaining === 20 && !skills.activate(0, game), "skill cooldown was altered by attack speed"); });
test("ion saw skill keeps its own display name", () => { const loadout = createLoadout({ modules: [{ moduleId: "special-chainsaw", x: 4, y: 3 }] }); const skill = new SkillSystem(loadout).getState()[0]; assert(skill.id === "ionSaw" && skill.name === "离子链锯", "ion saw skill name was replaced"); });
test("multiple sonic skills stay independent", () => { const loadout = createLoadout({ modules: [{ moduleId: "special-sonic", x: 4, y: 3 }, { moduleId: "special-sonic", x: 4, y: 5 }] }); const skills = new SkillSystem(loadout); const game = { state: "playing", waveCalls: [], startSonicWave: (duration) => game.waveCalls.push(duration) }; assert(skills.getState().length === 2, "duplicate sonic skills were not preserved"); assert(skills.activate(0, game) && skills.activate(1, game), "sonic skills cannot be activated independently"); assert(game.waveCalls.length === 2 && !skills.activate(0, game) && !skills.activate(1, game), "sonic skill cooldowns are shared"); });
test("sonic wave interval and top cleanup", () => { const game = Object.create(Game.prototype); game.elapsed = 0; game.sonicWaves = [{ spawnTimer: 0, nextY: 0, step: 38 }]; game.lasers = []; game.updateSonicWave(0.01); assert(SONIC_WAVE_CONFIG.spawnInterval === 0.15, "sonic interval is not 0.15 seconds"); assert(game.sonicWaves.length === 0 && game.lasers.length === 1, "top beam sequence did not finish cleanly"); game.updateSonicWave(SONIC_WAVE_CONFIG.beamLife); assert(game.lasers.length === 1 && game.lasers[0].life === 0, "beam damage lifetime was not separated from visual afterglow"); game.updateSonicWave(SONIC_WAVE_CONFIG.beamVisualLife); assert(game.lasers.length === 0, "top beam visual afterglow was not removed"); });
test("abyss bloom fires petals in all four directions", () => { const game = Object.create(Game.prototype); game.player = { x: 240, y: 400 }; game.enemies = []; game.projectiles = []; game.skyProtocols = []; game.azureSingularities = []; game.starRings = []; game.cryoHives = []; game.abyssBlooms = [{ duration: 2, pulse: 0, fireTimer: 0, moduleInstanceId: null }]; game.updateFusionSkills(0.01); assert(game.projectiles.length === 4 && game.projectiles.every((projectile) => projectile.kind === "abyssPetal" && projectile.team === "player"), "abyss bloom did not fire four petals"); const directions = game.projectiles.map((projectile) => Math.round(Math.atan2(projectile.vy, projectile.vx) * 100) / 100); assert(new Set(directions).size === 4, "abyss bloom petals did not cover four directions"); });
test("abyss bloom fires 150 percent faster", () => { const game = Object.create(Game.prototype); game.player = { x: 240, y: 400 }; game.enemies = []; game.projectiles = []; game.skyProtocols = []; game.azureSingularities = []; game.starRings = []; game.cryoHives = []; game.abyssBlooms = [{ duration: 2, pulse: 0, fireTimer: 0, moduleInstanceId: null }]; game.updateFusionSkills(0.01); game.updateFusionSkills(0.184); assert(game.projectiles.length === 8, "abyss bloom fire interval was not reduced by 150 percent frequency increase"); });
test("multiple abyss blooms remain independent", () => { const game = Object.create(Game.prototype); game.player = { x: 240, y: 400 }; game.enemies = []; game.projectiles = []; game.skyProtocols = []; game.azureSingularities = []; game.starRings = []; game.cryoHives = []; game.abyssBlooms = []; game.startAbyssBloom(2, "abyss-left"); game.startAbyssBloom(2, "abyss-right"); assert(game.abyssBlooms.length === 2, "multiple abyss bloom activations were collapsed"); game.updateFusionSkills(0.01); assert(game.projectiles.length === 8 && game.abyssBlooms.length === 2, "multiple abyss blooms did not fire independently"); });
test("fusion summons orbit their installed module origins", () => { const abyss = getModuleById("fusion-abyss-bloom"); const cryo = getModuleById("fusion-cryo-hive"); const game = Object.create(Game.prototype); game.player = { x: 240, y: 400, loadout: { corePosition: { x: 7, y: 7 } }, installedEntries: [{ instanceId: "abyss", x: 8, y: 7, module: abyss }, { instanceId: "cryo", x: 7, y: 8, module: cryo }] }; const abyssOrigin = game.getFusionSkillOrigin("abyss", "abyssBloom"); const cryoOrigin = game.getFusionSkillOrigin("cryo", "cryoHive"); assert(abyssOrigin.x !== game.player.x || abyssOrigin.y !== game.player.y, "abyss bloom still uses core origin"); assert(cryoOrigin.x !== game.player.x || cryoOrigin.y !== game.player.y, "cryo hive still uses core origin"); });
test("duplicate fusion modules keep their own origins", () => { const abyss = getModuleById("fusion-abyss-bloom"); const game = Object.create(Game.prototype); game.player = { x: 240, y: 400, loadout: { corePosition: { x: 7, y: 7 } }, installedEntries: [{ instanceId: "abyss-left", x: 6, y: 7, module: abyss }, { instanceId: "abyss-right", x: 8, y: 7, module: abyss }] }; const left = game.getFusionSkillOrigin("abyss-left", "abyssBloom"); const right = game.getFusionSkillOrigin("abyss-right", "abyssBloom"); assert(left.x < game.player.x && right.x > game.player.x && left.x !== right.x, "duplicate abyss blooms share one module origin"); });
test("ice shard applies a refreshing behavior slow", () => { const definition = { id: "test-slow", type: "striker", hp: 100, speed: 100, radius: 8, score: 1, shootInterval: 2 }; const enemy = new Enemy(definition, 100, { spawnY: 0 }); enemy.shootTimer = 1; enemy.applySlow({ multiplier: .67, duration: 3 }); enemy.applySlow({ multiplier: .67, duration: 3 }); enemy.update(1, { width: 480 }); assert(Math.abs(enemy.age - .67) < .001 && Math.abs(enemy.y - 67) < .001 && Math.abs(enemy.slowTimer - 2) < .001, "ice shard slow did not reduce all enemy behavior speed"); });
test("ice shard collision applies two damage and slow", () => { const definition = { id: "test-ice", type: "striker", hp: 100, speed: 100, radius: 8, score: 1, shootInterval: 2 }; const enemy = new Enemy(definition, 100, { spawnY: 100 }); const projectile = new Projectile({ x: 100, y: 100, vx: 0, vy: -1, damage: 2, radius: 4, color: "#a5f6ec", life: 1, team: "player", kind: "frostNeedle", pierce: true, slow: { multiplier: .67, duration: 3 } }); const result = new CollisionSystem().resolve({ player: { x: 300, y: 500, radius: 10 }, enemies: [enemy], projectiles: [projectile] }); assert(enemy.hp === 98 && enemy.slowTimer === 3 && result.destroyedEnemies.size === 0, "ice shard collision effect is incorrect"); });
test("ice module naming and payload configuration", () => { const ice = getModuleById("fusion-cryo-hive"); assert(ice.name === "冰凌" && ice.skill?.name === "冰凌" && ice.skill?.id === "cryoHive" && ice.skill?.duration === 3.5, "ice module name or duration configuration is incorrect"); });
test("updated module descriptions match current mechanics", () => { assert(getModuleById("special-chainsaw")?.description.includes("切除触碰范围内的敌方弹幕") && getModuleById("fusion-cryo-hive")?.description.includes("3.5 秒") && getModuleById("fusion-abyss-bloom")?.description.includes("同时向四个方向") && getModuleById("fusion-polar-saw")?.description.includes("每 0.7 秒"), "module descriptions are stale"); });
test("disconnected modules are pruned", () => { const repaired = pruneDisconnected(createLoadout({ modules: [{ moduleId: "weapon-nest", x: 3, y: 4 }, { moduleId: "weapon-ricochet", x: 4, y: 2 }] })); assert(repaired.removed.some(({ moduleId }) => moduleId === "weapon-ricochet"), "disconnected module remains"); });
test("circle collision", () => { assert(circleIntersects({ x: 0, y: 0, radius: 10 }, { x: 15, y: 0, radius: 6 }), "circle hit"); assert(!circleIntersects({ x: 0, y: 0, radius: 5 }, { x: 20, y: 0, radius: 5 }), "circle miss"); });
test("circle rectangle collision", () => { assert(circleRectIntersects({ x: 12, y: 12, radius: 5 }, { x: 0, y: 0, width: 10, height: 10 }), "corner hit"); assert(!circleRectIntersects({ x: 30, y: 30, radius: 4 }, { x: 0, y: 0, width: 10, height: 10 }), "rectangle miss"); });
test("enemy contact damages player but never destroys the enemy", () => { const player = { x: 100, y: 100, radius: 12 }; const enemy = { id: "contact", x: 100, y: 100, radius: 12, hp: 5, definition: { score: 10 } }; const result = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [] }); assert(result.playerDamage === GAME_CONFIG.projectile.enemyContactDamage, "contact damage missing"); assert(!result.destroyedEnemies.has(enemy) && enemy.hp === 5, "contact collision destroyed or damaged the enemy"); });
test("full assembled player body receives collision damage", () => { const loadout = createRawLoadout({ modules: [{ moduleId: "weapon-ricochet", x: 8, y: 7 }] }); const player = new Player({ x: 100, y: 100, stats: PLAYER_BASE_STATS, loadout }); const enemy = { id: "side-contact", x: 113, y: 100, radius: 5, hp: 5, definition: { score: 10 } }; const enemyBolt = new Projectile({ x: 113, y: 100, damage: 3, radius: 4, life: 1, team: "enemy" }); const contact = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [], freezeActive: false }); const bullet = new CollisionSystem().resolve({ player, enemies: [], projectiles: [enemyBolt], freezeActive: false }); assert(contact.playerDamage === GAME_CONFIG.projectile.enemyContactDamage && bullet.playerDamage === 3, "side module did not receive collision damage"); });
test("player and enemy damage values", () => { assert(PLAYER_BASE_STATS.maxHp === 100, "core hp should be 100"); assert(GAME_CONFIG.projectile.enemyDamage === 5 && GAME_CONFIG.projectile.enemyContactDamage === 5, "enemy damage should be 5"); });
test("module rarity assignments", () => { const expected = { "weapon-electric-whirlwind": "legendary", "weapon-nest": "legendary", "special-optical": "legendary", "special-zero": "legendary", "weapon-lightning-generator": "epic", "weapon-black-hole": "epic", "special-wingman": "epic", "special-sonic": "epic", "special-overclock": "epic", "special-polarity-reverse": "epic", "weapon-flame-crossbow": "epic", "weapon-water-shot": "epic", "weapon-ball-lightning": "rare", "weapon-psionic": "rare", "special-chainsaw": "rare", "special-energy-aggregator": "rare", "weapon-ricochet": "rare" }; for (const [id, rarity] of Object.entries(expected)) assert(getModuleById(id)?.rarity === rarity, `${id} rarity mismatch`); });
test("abyss bloom uses dark element", () => { const abyss = getModuleById("fusion-abyss-bloom"); assert(abyss.element === "dark" && getModuleElement(abyss) === "dark", "abyss bloom element is not dark"); });
test("thunder module is legendary", () => { assert(getModuleById("fusion-polar-saw")?.rarity === "legendary", "thunder rarity is not legendary"); });
test("thunder module fires every 0.7 seconds", () => { assert(getModuleById("fusion-polar-saw")?.behavior?.fireInterval === 0.7, "thunder fire interval is not 0.7 seconds"); });

test("new special module configuration", () => { const overclock = getModuleById("special-overclock"); const polarity = getModuleById("special-polarity-reverse"); const blackHole = getModuleById("weapon-black-hole"); assert(overclock?.footprint.cells.length === 4 && overclock.skill?.id === "overclock" && overclock.rarity === "epic", "overclock configuration"); assert(polarity?.footprint.cells.length === 4 && polarity.skill?.id === "polarityReverse" && polarity.rarity === "epic", "polarity configuration"); assert(blackHole?.footprint.cells.length === 4 && blackHole.behavior?.fireInterval === 7 && blackHole.behavior?.type === "blackHole" && blackHole.behavior.projectile.speed === 165 && blackHole.behavior.projectile.life === 5 && blackHole.behavior.projectile.damage === 0 && blackHole.behavior.projectile.blackHole.pullRadius === 66 && blackHole.behavior.projectile.blackHole.pullStrength === 210 && blackHole.behavior.projectile.blackHole.detonationDelay === 1 && blackHole.behavior.projectile.blackHole.explosionRadius === 37, "black hole configuration"); });
test("fusion definitions keep independent mechanics while disabled modules stay out of player loadouts", () => { const ids = ["fusion-abyss-bloom", "fusion-photon-chorus", "fusion-cryo-hive", "fusion-overflow-drive"]; const skills = ids.map((id) => getModuleById(id)?.skill?.id); assert(new Set(skills).size === ids.length && !skills.some((id) => ["sonicWave", "freeze", "decoy", "ionSaw", "overclock"].includes(id)), "fusion modules still reuse legacy active skills"); assert(ids.every((id) => getModuleById(id)?.beyondFusionOnly && getModuleById(id)?.fusionRecipe?.length), "fusion recipe metadata is missing"); const anchor = getModuleById("fusion-mirage-anchor"); const thunder = getModuleById("fusion-polar-saw"); const baseLightning = getModuleById("weapon-lightning-generator"); const abyss = getModuleById("fusion-abyss-bloom"); const system = new BeyondLightConeSystem(); assert(anchor.name === "时空锚点" && PLAYER_DISABLED_MODULE_IDS.has(anchor.id) && !MODULE_CONFIG.specials.includes(anchor) && !system.getBeyondRewardModules().some((module) => module.id === anchor.id), "时空锚点 should remain defined but disabled for players"); assert(getModuleById("fusion-overflow-drive") && PLAYER_DISABLED_MODULE_IDS.has("fusion-overflow-drive") && !MODULE_CONFIG.specials.includes(getModuleById("fusion-overflow-drive")) && !system.getBeyondRewardModules().some((module) => module.id === "fusion-overflow-drive"), "溢流驱动 should remain defined but disabled for players"); assert(thunder.name === "惊雷" && thunder.type === "weapon" && !thunder.skill && MODULE_CONFIG.weapons.includes(thunder) && thunder.behavior?.type === "lightning" && thunder.behavior.fireInterval < baseLightning.behavior.fireInterval && thunder.behavior.projectile.damage > baseLightning.behavior.projectile.damage && thunder.footprint.cells.length === 4 && thunder.fusionRecipe.length === 2 && thunder.fusionRecipe.every((item) => item.moduleId === "weapon-lightning-generator" && item.y === 1), "惊雷 automatic lightning configuration"); assert(abyss.skill?.id === "abyssBloom" && abyss.type === "special" && abyss.behavior === undefined, "深渊花冠 still uses its independent active mechanic"); });
test("overclock refreshes without stacking", () => { const game = Object.create(Game.prototype); game.player = { overclockTimer: 1 }; game.startOverclock(5); assert(game.player.overclockTimer === 5, "overclock did not refresh to five seconds"); game.startOverclock(5); assert(game.player.overclockTimer === 5, "repeated overclock changed the duration or stacked it"); const player = { x: 240, y: 700, stats: { attackSpeed: 1 }, overclockTimer: 5, loadout: createLoadout({ modules: [{ moduleId: "weapon-nest", x: 4, y: 3 }, { moduleId: "special-overclock", x: 3, y: 3 }, { moduleId: "special-overclock", x: 5, y: 3 }] }), canFireWeapon: () => true, armWeapon(_id, interval) { this.interval = interval; } }; new WeaponSystem().firePlayer(player, []); assert(Math.abs(player.interval - 6 / 1.8) < 0.001, "multiple overclock modules stacked their attack speed"); });
test("black hole captures bullets and detonates their damage", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-black-hole", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const hole = new WeaponSystem().firePlayer(player, [])[0]; const enemyBolt = new Projectile({ x: hole.x + 40, y: hole.y, vx: 0, vy: 80, damage: 6, radius: 4, color: "#ff557c", life: 3, team: "enemy" }); const game = Object.create(Game.prototype); game.projectiles = [hole, enemyBolt]; game.enemies = []; game.applyBlackHolePull(0.1); assert(enemyBolt.blackHoleCapturedBy === hole && hole.blackHole.capturedProjectiles.has(enemyBolt) && enemyBolt.blackHoleOrbit.radius > 0 && enemyBolt.blackHoleOrbit.radius < hole.blackHole.pullRadius && !hole.blackHole.slowed, "black hole capture orbit state"); const enemy = { id: "detonation-target", x: hole.x, y: hole.y, radius: 10, hp: 20, definition: { score: 1 }, takeDamage(amount) { this.hp -= amount; return false; } }; hole.life = 0; const result = new CollisionSystem().resolve({ player, enemies: [enemy], projectiles: [hole, enemyBolt] }); assert(enemy.hp === 14 && result.removedProjectiles.has(enemyBolt) && result.explosionEvents[0].kind === "blackHole" && result.explosionEvents[0].capturedCount === 1, "captured bullet did not detonate"); });
test("black hole detonates one second after capturing an enemy", () => { const player = { x: 240, y: 700, loadout: createLoadout({ modules: [{ moduleId: "weapon-black-hole", x: 4, y: 3 }] }), canFireWeapon: () => true, armWeapon: () => {} }; const hole = new WeaponSystem().firePlayer(player, [])[0]; const enemy = { id: "captured-enemy", x: hole.x, y: hole.y + 20, hp: 10 }; const game = Object.create(Game.prototype); game.projectiles = [hole]; game.enemies = [enemy]; game.applyBlackHolePull(0.1); assert(hole.blackHole.enemyCaptured && Math.abs(hole.blackHole.detonationTimer - 0.9) < 0.001, "enemy capture did not start one-second detonation timer"); game.applyBlackHolePull(0.9); assert(hole.life <= 0, "black hole did not detonate after one second"); });
test("flame crossbow spreads and applies nine burn ticks", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-flame-crossbow", x: 4, y: 3 }] }); const player = { x: 240, y: 700, stats: { attackSpeed: 1 }, loadout, canFireWeapon: () => true, armWeapon: () => {} }; const shots = new WeaponSystem().firePlayer(player, []); const guardian = ENEMY_CONFIG.find((enemy) => enemy.type === "guardian") ?? ENEMY_CONFIG.at(-1); const target = new Enemy(guardian, 240, { spawnY: 200 }); shots[1].x = target.x; shots[1].y = target.y; const result = new CollisionSystem().resolve({ player, enemies: [target], projectiles: shots }); const ticks = [...Array(3)].flatMap(() => target.updateBurn(1)); assert(shots.length === 3 && shots.every((shot) => shot.kind === "flameArrow") && result.damageEvents.some((event) => event.amount === 5 && event.element === "fire") && ticks.length === 9 && ticks.every((event) => event.amount === 1 && event.element === "fire"), "flame crossbow spread or burn failed"); });
test("water shot disappears and deals splash damage", () => { const loadout = createLoadout({ modules: [{ moduleId: "weapon-water-shot", x: 4, y: 3 }] }); const player = { x: 240, y: 700, stats: { attackSpeed: 1 }, loadout, canFireWeapon: () => true, armWeapon: () => {} }; const shots = new WeaponSystem().firePlayer(player, []); const guardian = ENEMY_CONFIG.find((enemy) => enemy.type === "guardian") ?? ENEMY_CONFIG.at(-1); const target = new Enemy(guardian, 240, { spawnY: 200 }); const nearby = new Enemy(guardian, 260, { spawnY: 200 }); shots[0].x = target.x; shots[0].y = target.y; const result = new CollisionSystem().resolve({ player, enemies: [target, nearby], projectiles: shots }); assert(shots[0].kind === "waterShot" && result.removedProjectiles.has(shots[0]) && target.hp === target.maxHp - 3 && nearby.hp === nearby.maxHp - 2 && result.damageEvents.some((event) => event.amount === 2 && event.element === "water"), "water splash behavior failed"); });
const failed = results.filter((line) => line.startsWith("FAIL")).length; output.className = failed ? "fail" : "pass"; output.textContent = `${failed ? "Some tests failed" : "All tests passed"}\n\n${results.join("\n")}`;
